name: Test .NET on macOS-15 Runners #12520

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:

jobs:
  test-dotnet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, macos-15-arm64]
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Show .NET version
        run: dotnet --version
